#ifndef __TABLES_H__
#define __TABLES_H__

#include "types.h"

enum Opcodes
{
	NOP=0, 		LD_BC_nn, 	LD_cBC_A, INC_BC, INC_B, 	DEC_B, 	LD_B_n, 	RLCA,
	EX_AF_SAF,	ADD_HL_BC,	LD_A_cBC, DEC_BC, INC_C, 	DEC_C, 	LD_C_n, 	RRCA,
	DJNZ_d,		LD_DE_nn,	LD_cDE_A, INC_DE, INC_D, 	DEC_D, 	LD_D_n, 	RLA,
	JR_d,		ADD_HL_DE,	LD_A_cDE, DEC_DE, INC_E, 	DEC_E, 	LD_E_n, 	RRA,		
	JRNZ_d,		LD_HL_nn,	LD_cnn_HL,INC_HL, INC_H, 	DEC_H, 	LD_H_n, 	DAA,
	JRZ_d,		ADD_HL_HL,	LD_HL_cnn,DEC_HL, INC_L, 	DEC_L, 	LD_L_n, 	CPL,
	JRNC_d,		LD_SP_nn,	LD_cnn_A, INC_SP, INC_cHL , DEC_cHL,LD_cHL_n,	SCF,
	JRC_d,		ADD_HL_SP,	LD_A_cnn, DEC_SP, INC_A,	DEC_A,	LD_A_n,		CCF,
	
	LD_B_B,		LD_B_C,		LD_B_D,		LD_B_E,		LD_B_H,		LD_B_L,		LD_B_cHL ,	LD_B_A,
	LD_C_B,		LD_C_C,		LD_C_D,		LD_C_E,		LD_C_H,		LD_C_L,		LD_C_cHL ,	LD_C_A,
	LD_D_B,		LD_D_C,		LD_D_D,		LD_D_E,		LD_D_H,		LD_D_L,		LD_D_cHL ,	LD_D_A,
	LD_E_B,		LD_E_C,		LD_E_D,		LD_E_E,		LD_E_H,		LD_E_L,		LD_E_cHL ,	LD_E_A,
	LD_H_B,		LD_H_C,		LD_H_D,		LD_H_E,		LD_H_H,		LD_H_L,		LD_H_cHL ,	LD_H_A,
	LD_L_B,		LD_L_C,		LD_L_D,		LD_L_E,		LD_L_H,		LD_L_L,		LD_L_cHL ,	LD_L_A,
	LD_cHL_B,	LD_cHL_C,	LD_cHL_D,	LD_cHL_E,	LD_cHL_H,	LD_cHL_L,	HALT,	LD_cHL_A,
	LD_A_B,		LD_A_C,		LD_A_D,		LD_A_E,		LD_A_H,		LD_A_L,		LD_A_cHL ,	LD_A_A,

	ADD_A_B, ADD_A_C, ADD_A_D, ADD_A_E, ADD_A_H, ADD_A_L, ADD_A_cHL , ADD_A_A,
	ADC_A_B, ADC_A_C, ADC_A_D, ADC_A_E, ADC_A_H, ADC_A_L, ADC_A_cHL , ADC_A_A,
	SUB_A_B, SUB_A_C, SUB_A_D, SUB_A_E, SUB_A_H, SUB_A_L, SUB_A_cHL , SUB_A_A,
	SBC_A_B, SBC_A_C, SBC_A_D, SBC_A_E, SBC_A_H, SBC_A_L, SBC_A_cHL , SBC_A_A,
	AND_A_B, AND_A_C, AND_A_D, AND_A_E, AND_A_H, AND_A_L, AND_A_cHL , AND_A_A,
	XOR_A_B, XOR_A_C, XOR_A_D, XOR_A_E, XOR_A_H, XOR_A_L, XOR_A_cHL , XOR_A_A,
	OR_A_B,  OR_A_C,  OR_A_D,  OR_A_E,  OR_A_H,  OR_A_L,  OR_A_cHL ,  OR_A_A,
	CP_A_B,  CP_A_C,  CP_A_D,  CP_A_E,  CP_A_H,  CP_A_L,  CP_A_cHL ,  CP_A_A,
	
	RETNZ,	POP_BC,		JPNZ_nn,	JP_nn, 		CALLNZ_nn,	PUSH_BC, ADD_A_n, RST0,
	RETZ,	RET_,		JPZ_nn,	 	CDPREFIX,	CALLZ_nn,	CALL_nn, ADC_A_n, RST08,
	RETNC,  POP_DE,		JPNC_nn,	OUT_n_A,	CALLNC_nn,	PUSH_DE, SUB_n,	  RST10,
	RETC,	EXX,		JPC_nn,		IN_A_n,		CALLC_nn,	PREFIX,	 SBC_A_n, RST18,
	RETPO,	POP_HL,		JPPO_nn,	EX_cSP_HL,	CALLPO_nn,	PUSH_HL, AND_n,   RST20,
	RETPE,	JP_cHL , 	JPPE_nn,	EX_DE_HL,	CALLPE_nn,	DDPREFIX,XOR_n,   RST28,	
	RETP,	POP_AF, 	JPP_nn,		DI,			CALLP_nn,	PUSH_AF, OR_n,	  RST30,
	RETM,	LD_SP_HL,	JPM_nn,		EI,			CALLM_nn,	FDPREFIX,CP_n,	  RST38,
};


enum OpcodesCB
{
	RLC_B=0,RLC_C,RLC_D,RLC_E,RLC_H,RLC_L,RLC_cHL ,RLC_A,
	RRC_B,RRC_C,RRC_D,RRC_E,RRC_H,RRC_L,RRC_cHL ,RRC_A,
	RL_B,RL_C,RL_D,RL_E,RL_H,RL_L,RL_cHL ,RL_A,
	RR_B,RR_C,RR_D,RR_E,RR_H,RR_L,RR_cHL ,RR_A,
	SLA_B,SLA_C,SLA_D,SLA_E,SLA_H,SLA_L,SLA_cHL ,SLA_A,
	SRA_B,SRA_C,SRA_D,SRA_E,SRA_H,SRA_L,SRA_cHL ,SRA_A,
	SLL_B,SLL_C,SLL_D,SLL_E,SLL_H,SLL_L,SLL_cHL ,SLL_A,
	SRL_B,SRL_C,SRL_D,SRL_E,SRL_H,SRL_L,SRL_cHL ,SRL_A,
	BIT0_B,BIT0_C,BIT0_D,BIT0_E,BIT0_H,BIT0_L,BIT0_cHL ,BIT0_A,
	BIT1_B,BIT1_C,BIT1_D,BIT1_E,BIT1_H,BIT1_L,BIT1_cHL ,BIT1_A,
	BIT2_B,BIT2_C,BIT2_D,BIT2_E,BIT2_H,BIT2_L,BIT2_cHL ,BIT2_A,
	BIT3_B,BIT3_C,BIT3_D,BIT3_E,BIT3_H,BIT3_L,BIT3_cHL ,BIT3_A,
	BIT4_B,BIT4_C,BIT4_D,BIT4_E,BIT4_H,BIT4_L,BIT4_cHL ,BIT4_A,
	BIT5_B,BIT5_C,BIT5_D,BIT5_E,BIT5_H,BIT5_L,BIT5_cHL ,BIT5_A,
	BIT6_B,BIT6_C,BIT6_D,BIT6_E,BIT6_H,BIT6_L,BIT6_cHL ,BIT6_A,
	BIT7_B,BIT7_C,BIT7_D,BIT7_E,BIT7_H,BIT7_L,BIT7_cHL ,BIT7_A,
	RES0_B,RES0_C,RES0_D,RES0_E,RES0_H,RES0_L,RES0_cHL ,RES0_A,
	RES1_B,RES1_C,RES1_D,RES1_E,RES1_H,RES1_L,RES1_cHL ,RES1_A,
	RES2_B,RES2_C,RES2_D,RES2_E,RES2_H,RES2_L,RES2_cHL ,RES2_A,
	RES3_B,RES3_C,RES3_D,RES3_E,RES3_H,RES3_L,RES3_cHL ,RES3_A,
	RES4_B,RES4_C,RES4_D,RES4_E,RES4_H,RES4_L,RES4_cHL ,RES4_A,
	RES5_B,RES5_C,RES5_D,RES5_E,RES5_H,RES5_L,RES5_cHL ,RES5_A,
	RES6_B,RES6_C,RES6_D,RES6_E,RES6_H,RES6_L,RES6_cHL ,RES6_A,
	RES7_B,RES7_C,RES7_D,RES7_E,RES7_H,RES7_L,RES7_cHL ,RES7_A,
	SET0_B,SET0_C,SET0_D,SET0_E,SET0_H,SET0_L,SET0_cHL ,SET0_A,
	SET1_B,SET1_C,SET1_D,SET1_E,SET1_H,SET1_L,SET1_cHL ,SET1_A,
	SET2_B,SET2_C,SET2_D,SET2_E,SET2_H,SET2_L,SET2_cHL ,SET2_A,
	SET3_B,SET3_C,SET3_D,SET3_E,SET3_H,SET3_L,SET3_cHL ,SET3_A,
	SET4_B,SET4_C,SET4_D,SET4_E,SET4_H,SET4_L,SET4_cHL ,SET4_A,
	SET5_B,SET5_C,SET5_D,SET5_E,SET5_H,SET5_L,SET5_cHL ,SET5_A,
	SET6_B,SET6_C,SET6_D,SET6_E,SET6_H,SET6_L,SET6_cHL ,SET6_A,
	SET7_B,SET7_C,SET7_D,SET7_E,SET7_H,SET7_L,SET7_cHL ,SET7_A,
};

enum OpcodesDD
{
	DD00,DD01,DD02,DD03,DD04,DD05,DD06,DD07,
	DD08,ADD_IX_BC,DD0A,DD0B,DD0C,DD0D,DD0E,DD0F,
	DD10,DD11,DD12,DD13,DD14,DD15,DD16,DD17,
	DD18,ADD_IX_DE,DD1A,DD1B,DD1C,DD1D,DD1E,DD1F,
	DD20,LD_IX_nn,LD_cnn_IX,INC_IX,INC_IXH,DEC_IXH,LD_IXH_n,DD27,
	DD28,ADD_IX_IX,LD_IX_cnn,DEC_IX,INC_IXL,DEC_IXL,LD_IXL_n,DD2F,
	DD30,DD31,DD32,DD33,INC_cIXd,DEC_cIXd,LD_cIXd_n,DD37,
	DD38,ADD_IX_SP,DD3A,DD3B,DD3C,DD3D,DD3E,DD3F,
	DD40,DD41,DD42,DD43,LD_B_IXH,LD_B_IXL,LD_B_cIXd,DD47,
	DD48,DD49,DD4A,DD4B,LD_C_IXH,LD_C_IXL,LD_C_cIXd,DD4F,
	DD50,DD51,DD52,DD53,LD_D_IXH,LD_D_IXL,LD_D_cIXd,DD57,
	DD58,DD59,DD5A,DD5B,LD_E_IXH,LD_E_IXL,LD_E_cIXd,DD5F,
	LD_IXH_B,LD_IXH_C,LD_IXH_D,LD_IXH_E,LD_IXH_IXH,LD_IXH_IXL,LD_H_cIXd,LD_IXH_A,
	LD_IXL_B,LD_IXL_C,LD_IXL_D,LD_IXL_E,LD_IXL_IXH,LD_IXL_IXL,LD_L_cIXd,LD_IXL_A,
	LD_cIXd_B,LD_cIXd_C,LD_cIXd_D,LD_cIXd_E,LD_cIXd_H,LD_cIXd_L,DD76,LD_cIXd_A,
	DD78,DD79,DD7A,DD7B,LD_A_IXH,LD_A_IXL,LD_A_cIXd,DD7F,
	DD80,DD81,DD82,DD83,ADD_A_IXH,ADD_A_IXL,ADD_A_cIXd,DD87,
	DD88,DD89,DD8A,DD8B,ADC_A_IXH,ADC_A_IXL,ADC_A_cIXd,DD8F,
	DD90,DD91,DD92,DD93,SUB_A_IXH,SUB_A_IXL,SUB_A_cIXd,DD97,
	DD98,DD99,DD9A,DD9B,SBC_A_IXH,SBC_A_IXL,SBC_A_cIXd,DD9F,
	DDA0,DDA1,DDA2,DDA3,AND_IXH,AND_IXL,AND_cIXd,DDA7,
	DDA8,DDA9,DDAA,DDAB,XOR_IXH,XOR_IXL,XOR_cIXd,DDAF,
	DDB0,DDB1,DDB2,DDB3,OR_IXH,OR_IXL,OR_cIXd,DDB7,
	DDB8,DDB9,DDBA,DDBB,CP_IXH,CP_IXL,CP_cIXd,DDBF,
	DDC0,DDC1,DDC2,DDC3,DDC4,DDC5,DDC6,DDC7,
	DDC8,DDC9,DDCA,DDCB,DDCC,DDCD,DDCE,DDCF,
	DDD0,DDD1,DDD2,DDD3,DDD4,DDD5,DDD6,DDD7,
	DDD8,DDD9,DDDA,DDDB,DDDC,DDDD,DDDE,DDDF,
	DDE0,POP_IX,DDE2,EX_cSP_IX,DDE4,PUSH_IX,DDE6,DDE7,
	DDE8,JP_cIX,DDEA,DDEB,DDEC,DDED,DDEE,DDEF,
	DDF0,DDF1,DDF2,DDF3,DDF4,DDF5,DDF6,DDF7,
	DDF8,LD_SP_IX,DDFA,DDFB,DDFC,DDFD,DDFE,DDFF,
};




enum OpcodesFD
{
	FD00,FD01,FD02,FD03,FD04,FD05,FD06,FD07,
		FD08,ADD_IY_BC,FD0A,FD0B,FD0C,FD0D,FD0E,FD0F,
		FD10,FD11,FD12,FD13,FD14,FD15,FD16,FD17,
		FD18,ADD_IY_DE,FD1A,FD1B,FD1C,FD1D,FD1E,FD1F,
		FD20,LD_IY_nn,LD_cnn_IY,INC_IY,INC_IYH,DEC_IYH,LD_IYH_n,FD27,
		FD28,ADD_IY_IY,LD_IY_cnn,DEC_IY,INC_IYL,DEC_IYL,LD_IYL_n,FD2F,
		FD30,FD31,FD32,FD33,INC_cIYd,DEC_cIYd,LD_cIYd_n,FD37,
		FD38,ADD_IY_SP,FD3A,FD3B,FD3C,FD3D,FD3E,FD3F,
		FD40,FD41,FD42,FD43,LD_B_IYH,LD_B_IYL,LD_B_cIYd,FD47,
		FD48,FD49,FD4A,FD4B,LD_C_IYH,LD_C_IYL,LD_C_cIYd,FD4F,
		FD50,FD51,FD52,FD53,LD_D_IYH,LD_D_IYL,LD_D_cIYd,FD57,
		FD58,FD59,FD5A,FD5B,LD_E_IYH,LD_E_IYL,LD_E_cIYd,FD5F,
		LD_IYH_B,LD_IYH_C,LD_IYH_D,LD_IYH_E,LD_IYH_IYH,LD_IYH_IYL,LD_H_cIYd,LD_IYH_A,
		LD_IYL_B,LD_IYL_C,LD_IYL_D,LD_IYL_E,LD_IYL_IYH,LD_IYL_IYL,LD_L_cIYd,LD_IYL_A,
		LD_cIYd_B,LD_cIYd_C,LD_cIYd_D,LD_cIYd_E,LD_cIYd_H,LD_cIYd_L,FD76,LD_cIYd_A,
		FD78,FD79,FD7A,FD7B,LD_A_IYH,LD_A_IYL,LD_A_cIYd,FD7F,
		FD80,FD81,FD82,FD83,ADD_A_IYH,ADD_A_IYL,ADD_A_cIYd,FD87,
		FD88,FD89,FD8A,FD8B,ADC_A_IYH,ADC_A_IYL,ADC_A_cIYd,FD8F,
		FD90,FD91,FD92,FD93,SUB_A_IYH,SUB_A_IYL,SUB_A_cIYd,FD97,
		FD98,FD99,FD9A,FD9B,SBC_A_IYH,SBC_A_IYL,SBC_A_cIYd,FD9F,
		FDA0,FDA1,FDA2,FDA3,AND_IYH,AND_IYL,AND_cIYd,FDA7,
		FDA8,FDA9,FDAA,FDAB,XOR_IYH,XOR_IYL,XOR_cIYd,FDAF,
		FDB0,FDB1,FDB2,FDB3,OR_IYH,OR_IYL,OR_cIYd,FDB7,
		FDB8,FDB9,FDBA,FDBB,CP_IYH,CP_IYL,CP_cIYd,FDBF,
		FDC0,FDC1,FDC2,FDC3,FDC4,FDC5,FDC6,FDC7,
		FDC8,FDC9,FDCA,FDCB,FDCC,FDCD,FDCE,FDCF,
		FDD0,FDD1,FDD2,FDD3,FDD4,FDD5,FDD6,FDD7,
		FDD8,FDD9,FDDA,FDDB,FDDC,FDDD,FDDE,FDDF,
		FDE0,POP_IY,FDE2,EX_cSP_IY,FDE4,PUSH_IY,FDE6,FDE7,
		FDE8,JP_cIY,FDEA,FDEB,FDEC,FDED,FDEE,FDEF,
		FDF0,FDF1,FDF2,FDF3,FDF4,FDF5,FDF6,FDF7,
		FDF8,LD_SP_IY,FDFA,FDFB,FDFC,FDFD,FDFE,FDFF,
};




enum OpcodesED
{

	DB_00,DB_01,DB_02,DB_03,DB_04,DB_05,DB_06,DB_07,
	DB_08,DB_09,DB_0A,DB_0B,DB_0C,DB_0D,DB_0E,DB_0F,
	DB_10,DB_11,DB_12,DB_13,DB_14,DB_15,DB_16,DB_17,
	DB_18,DB_19,DB_1A,DB_1B,DB_1C,DB_1D,DB_1E,DB_1F,
	DB_20,DB_21,DB_22,DB_23,DB_24,DB_25,DB_26,DB_27,
	DB_28,DB_29,DB_2A,DB_2B,DB_2C,DB_2D,DB_2E,DB_2F,
	DB_30,DB_31,DB_32,DB_33,DB_34,DB_35,DB_36,DB_37,
	DB_38,DB_39,DB_3A,DB_3B,DB_3C,DB_3D,DB_3E,DB_3F,
	IN_B_cC,OUT_cC_B,SBC_HL_BC,LD_cnn_BC,NEG,RETN,IM_0,LD_I_A,
	IN_C_cC,OUT_cC_C,ADC_HL_BC,LD_BC_cnn,DB_4C,RETI,DB_,LD_R_A,
	IN_D_cC,OUT_cC_D,SBC_HL_DE,LD_cnn_DE,DB_54,DB_55,IM_1,LD_A_I,
	IN_E_cC,OUT_cC_E,ADC_HL_DE,LD_DE_cnn,DB_5C,DB_5D,IM_2,LD_A_R,
	IN_H_cC,OUT_cC_H,SBC_HL_HL,LD_cnn_HL_ex,DB_64,DB_65,DB_66,RRD,
	IN_L_cC,OUT_cC_L,ADC_HL_HL,LD_HL_cnn_ex,DB_6C,DB_6D,DB_6E,RLD,
	IN_F_cC,DB_71,SBC_HL_SP,LD_cnn_SP,DB_74,DB_75,DB_76,DB_77,
	IN_A_cC,OUT_cC_A,ADC_HL_SP,LD_SP_cnn,DB_7C,DB_7D,DB_7E,DB_7F,
	DB_80,DB_81,DB_82,DB_83,DB_84,DB_85,DB_86,DB_87,
	DB_88,DB_89,DB_8A,DB_8B,DB_8C,DB_8D,DB_8E,DB_8F,
	DB_90,DB_91,DB_92,DB_93,DB_94,DB_95,DB_96,DB_97,
	DB_98,DB_99,DB_9A,DB_9B,DB_9C,DB_9D,DB_9E,DB_9F,
	LDI,CPI,INI,OUTI,DB_A4,DB_A5,DB_A6,DB_A7,
	LDD,CPD,IND,OUTD,DB_AC,DB_AD,DB_AE,DB_AF,
	LDIR,CPIR,INIR,OTIR,DB_B4,DB_B5,DB_B6,DB_B7,
	LDDR,CPDR,INDR,OTDR,DB_BC,DB_BD,DB_BE,DB_BF,
	DB_C0,DB_C1,DB_C2,DB_C3,DB_C4,DB_C5,DB_C6,DB_C7,
	DB_C8,DB_C9,DB_CA,DB_CB,DB_CC,DB_CD,DB_CE,DB_CF,
	DB_D0,DB_D1,DB_D2,DB_D3,DB_D4,DB_D5,DB_D6,DB_D7,
	DB_D8,DB_D9,DB_DA,DB_DB,DB_DC,DB_DD,DB_DE,DB_DF,
	DB_E0,DB_E1,DB_E2,DB_E3,DB_E4,DB_E5,DB_E6,DB_E7,
	DB_E8,DB_E9,DB_EA,DB_EB,DB_EC,DB_ED,DB_EE,DB_EF,
	DB_F0,DB_F1,DB_F2,DB_F3,DB_F4,DB_F5,DB_F6,DB_F7,
	DB_F8,DB_F9,DB_FA,DB_FB,DB_FC,DB_FD,DB_FE,DB_FF
};



enum OpcodesDDCB
{
	RLC_IXd_B=0,RLC_IXd_C,RLC_IXd_D,RLC_IXd_E,RLC_IXd_H,RLC_IXd_L,RLC_IXd,RLC_IXd_A,
	RRC_IXd_B,RRC_IXd_C,RRC_IXd_D,RRC_IXd_E,RRC_IXd_H,RRC_IXd_L,  RRC_IXd ,RRC_IXd_A,
	RL_IXd_B,RL_IXd_C,RL_IXd_D,RL_IXd_E,RL_IXd_H,RL_IXd_L,        RL_IXd ,RL_IXd_A,
	RR_IXd_B,RR_IXd_C,RR_IXd_D,RR_IXd_E,RR_IXd_H,RR_IXd_L,        RR_IXd ,RR_IXd_A,
	SLA_IXd_B,SLA_IXd_C,SLA_IXd_D,SLA_IXd_E,SLA_IXd_H,SLA_IXd_L,  SLA_IXd ,SLA_IXd_A,
	SRA_IXd_B,SRA_IXd_C,SRA_IXd_D,SRA_IXd_E,SRA_IXd_H,SRA_IXd_L,  SRA_IXd ,SRA_IXd_A,
	SLL_IXd_B,SLL_IXd_C,SLL_IXd_D,SLL_IXd_E,SLL_IXd_H,SLL_IXd_L,  SLL_IXd ,SLL_IXd_A,
	SRL_IXd_B,SRL_IXd_C,SRL_IXd_D,SRL_IXd_E,SRL_IXd_H,SRL_IXd_L,SRL_IXd ,SRL_IXd_A,
	BIT0_IXd_B,BIT0_IXd_C,BIT0_IXd_D,BIT0_IXd_E,BIT0_IXd_H,BIT0_IXd_L,BIT0_IXd ,BIT0_IXd_A,
	BIT1_IXd_B,BIT1_IXd_C,BIT1_IXd_D,BIT1_IXd_E,BIT1_IXd_H,BIT1_IXd_L,BIT1_IXd ,BIT1_IXd_A,
	BIT2_IXd_B,BIT2_IXd_C,BIT2_IXd_D,BIT2_IXd_E,BIT2_IXd_H,BIT2_IXd_L,BIT2_IXd ,BIT2_IXd_A,
	BIT3_IXd_B,BIT3_IXd_C,BIT3_IXd_D,BIT3_IXd_E,BIT3_IXd_H,BIT3_IXd_L,BIT3_IXd ,BIT3_IXd_A,
	BIT4_IXd_B,BIT4_IXd_C,BIT4_IXd_D,BIT4_IXd_E,BIT4_IXd_H,BIT4_IXd_L,BIT4_IXd ,BIT4_IXd_A,
	BIT5_IXd_B,BIT5_IXd_C,BIT5_IXd_D,BIT5_IXd_E,BIT5_IXd_H,BIT5_IXd_L,BIT5_IXd ,BIT5_IXd_A,
	BIT6_IXd_B,BIT6_IXd_C,BIT6_IXd_D,BIT6_IXd_E,BIT6_IXd_H,BIT6_IXd_L,BIT6_IXd ,BIT6_IXd_A,
	BIT7_IXd_B,BIT7_IXd_C,BIT7_IXd_D,BIT7_IXd_E,BIT7_IXd_H,BIT7_IXd_L,BIT7_IXd ,BIT7_IXd_A,
	RES0_IXd_B,RES0_IXd_C,RES0_IXd_D,RES0_IXd_E,RES0_IXd_H,RES0_IXd_L,RES0_IXd ,RES0_IXd_A,
	RES1_IXd_B,RES1_IXd_C,RES1_IXd_D,RES1_IXd_E,RES1_IXd_H,RES1_IXd_L,RES1_IXd ,RES1_IXd_A,
	RES2_IXd_B,RES2_IXd_C,RES2_IXd_D,RES2_IXd_E,RES2_IXd_H,RES2_IXd_L,RES2_IXd ,RES2_IXd_A,
	RES3_IXd_B,RES3_IXd_C,RES3_IXd_D,RES3_IXd_E,RES3_IXd_H,RES3_IXd_L,RES3_IXd ,RES3_IXd_A,
	RES4_IXd_B,RES4_IXd_C,RES4_IXd_D,RES4_IXd_E,RES4_IXd_H,RES4_IXd_L,RES4_IXd ,RES4_IXd_A,
	RES5_IXd_B,RES5_IXd_C,RES5_IXd_D,RES5_IXd_E,RES5_IXd_H,RES5_IXd_L,RES5_IXd ,RES5_IXd_A,
	RES6_IXd_B,RES6_IXd_C,RES6_IXd_D,RES6_IXd_E,RES6_IXd_H,RES6_IXd_L,RES6_IXd ,RES6_IXd_A,
	RES7_IXd_B,RES7_IXd_C,RES7_IXd_D,RES7_IXd_E,RES7_IXd_H,RES7_IXd_L,RES7_IXd ,RES7_IXd_A,
	SET0_IXd_B,SET0_IXd_C,SET0_IXd_D,SET0_IXd_E,SET0_IXd_H,SET0_IXd_L,SET0_IXd ,SET0_IXd_A,
	SET1_IXd_B,SET1_IXd_C,SET1_IXd_D,SET1_IXd_E,SET1_IXd_H,SET1_IXd_L,SET1_IXd ,SET1_IXd_A,
	SET2_IXd_B,SET2_IXd_C,SET2_IXd_D,SET2_IXd_E,SET2_IXd_H,SET2_IXd_L,SET2_IXd ,SET2_IXd_A,
	SET3_IXd_B,SET3_IXd_C,SET3_IXd_D,SET3_IXd_E,SET3_IXd_H,SET3_IXd_L,SET3_IXd ,SET3_IXd_A,
	SET4_IXd_B,SET4_IXd_C,SET4_IXd_D,SET4_IXd_E,SET4_IXd_H,SET4_IXd_L,SET4_IXd ,SET4_IXd_A,
	SET5_IXd_B,SET5_IXd_C,SET5_IXd_D,SET5_IXd_E,SET5_IXd_H,SET5_IXd_L,SET5_IXd ,SET5_IXd_A,
	SET6_IXd_B,SET6_IXd_C,SET6_IXd_D,SET6_IXd_E,SET6_IXd_H,SET6_IXd_L,SET6_IXd ,SET6_IXd_A,
	SET7_IXd_B,SET7_IXd_C,SET7_IXd_D,SET7_IXd_E,SET7_IXd_H,SET7_IXd_L,SET7_IXd ,SET7_IXd_A,
};


enum OpcodesFDCB
{
	RLC_IYd_B=0,RLC_IYd_C,RLC_IYd_D,RLC_IYd_E,RLC_IYd_H,RLC_IYd_L,RLC_IYd,RLC_IYd_A,
		RRC_IYd_B,RRC_IYd_C,RRC_IYd_D,RRC_IYd_E,RRC_IYd_H,RRC_IYd_L,  RRC_IYd ,RRC_IYd_A,
		RL_IYd_B,RL_IYd_C,RL_IYd_D,RL_IYd_E,RL_IYd_H,RL_IYd_L,        RL_IYd ,RL_IYd_A,
		RR_IYd_B,RR_IYd_C,RR_IYd_D,RR_IYd_E,RR_IYd_H,RR_IYd_L,        RR_IYd ,RR_IYd_A,
		SLA_IYd_B,SLA_IYd_C,SLA_IYd_D,SLA_IYd_E,SLA_IYd_H,SLA_IYd_L,  SLA_IYd ,SLA_IYd_A,
		SRA_IYd_B,SRA_IYd_C,SRA_IYd_D,SRA_IYd_E,SRA_IYd_H,SRA_IYd_L,  SRA_IYd ,SRA_IYd_A,
		SLL_IYd_B,SLL_IYd_C,SLL_IYd_D,SLL_IYd_E,SLL_IYd_H,SLL_IYd_L,  SLL_IYd ,SLL_IYd_A,
		SRL_IYd_B,SRL_IYd_C,SRL_IYd_D,SRL_IYd_E,SRL_IYd_H,SRL_IYd_L,SRL_IYd ,SRL_IYd_A,
		BIT0_IYd_B,BIT0_IYd_C,BIT0_IYd_D,BIT0_IYd_E,BIT0_IYd_H,BIT0_IYd_L,BIT0_IYd ,BIT0_IYd_A,
		BIT1_IYd_B,BIT1_IYd_C,BIT1_IYd_D,BIT1_IYd_E,BIT1_IYd_H,BIT1_IYd_L,BIT1_IYd ,BIT1_IYd_A,
		BIT2_IYd_B,BIT2_IYd_C,BIT2_IYd_D,BIT2_IYd_E,BIT2_IYd_H,BIT2_IYd_L,BIT2_IYd ,BIT2_IYd_A,
		BIT3_IYd_B,BIT3_IYd_C,BIT3_IYd_D,BIT3_IYd_E,BIT3_IYd_H,BIT3_IYd_L,BIT3_IYd ,BIT3_IYd_A,
		BIT4_IYd_B,BIT4_IYd_C,BIT4_IYd_D,BIT4_IYd_E,BIT4_IYd_H,BIT4_IYd_L,BIT4_IYd ,BIT4_IYd_A,
		BIT5_IYd_B,BIT5_IYd_C,BIT5_IYd_D,BIT5_IYd_E,BIT5_IYd_H,BIT5_IYd_L,BIT5_IYd ,BIT5_IYd_A,
		BIT6_IYd_B,BIT6_IYd_C,BIT6_IYd_D,BIT6_IYd_E,BIT6_IYd_H,BIT6_IYd_L,BIT6_IYd ,BIT6_IYd_A,
		BIT7_IYd_B,BIT7_IYd_C,BIT7_IYd_D,BIT7_IYd_E,BIT7_IYd_H,BIT7_IYd_L,BIT7_IYd ,BIT7_IYd_A,
		RES0_IYd_B,RES0_IYd_C,RES0_IYd_D,RES0_IYd_E,RES0_IYd_H,RES0_IYd_L,RES0_IYd ,RES0_IYd_A,
		RES1_IYd_B,RES1_IYd_C,RES1_IYd_D,RES1_IYd_E,RES1_IYd_H,RES1_IYd_L,RES1_IYd ,RES1_IYd_A,
		RES2_IYd_B,RES2_IYd_C,RES2_IYd_D,RES2_IYd_E,RES2_IYd_H,RES2_IYd_L,RES2_IYd ,RES2_IYd_A,
		RES3_IYd_B,RES3_IYd_C,RES3_IYd_D,RES3_IYd_E,RES3_IYd_H,RES3_IYd_L,RES3_IYd ,RES3_IYd_A,
		RES4_IYd_B,RES4_IYd_C,RES4_IYd_D,RES4_IYd_E,RES4_IYd_H,RES4_IYd_L,RES4_IYd ,RES4_IYd_A,
		RES5_IYd_B,RES5_IYd_C,RES5_IYd_D,RES5_IYd_E,RES5_IYd_H,RES5_IYd_L,RES5_IYd ,RES5_IYd_A,
		RES6_IYd_B,RES6_IYd_C,RES6_IYd_D,RES6_IYd_E,RES6_IYd_H,RES6_IYd_L,RES6_IYd ,RES6_IYd_A,
		RES7_IYd_B,RES7_IYd_C,RES7_IYd_D,RES7_IYd_E,RES7_IYd_H,RES7_IYd_L,RES7_IYd ,RES7_IYd_A,
		SET0_IYd_B,SET0_IYd_C,SET0_IYd_D,SET0_IYd_E,SET0_IYd_H,SET0_IYd_L,SET0_IYd ,SET0_IYd_A,
		SET1_IYd_B,SET1_IYd_C,SET1_IYd_D,SET1_IYd_E,SET1_IYd_H,SET1_IYd_L,SET1_IYd ,SET1_IYd_A,
		SET2_IYd_B,SET2_IYd_C,SET2_IYd_D,SET2_IYd_E,SET2_IYd_H,SET2_IYd_L,SET2_IYd ,SET2_IYd_A,
		SET3_IYd_B,SET3_IYd_C,SET3_IYd_D,SET3_IYd_E,SET3_IYd_H,SET3_IYd_L,SET3_IYd ,SET3_IYd_A,
		SET4_IYd_B,SET4_IYd_C,SET4_IYd_D,SET4_IYd_E,SET4_IYd_H,SET4_IYd_L,SET4_IYd ,SET4_IYd_A,
		SET5_IYd_B,SET5_IYd_C,SET5_IYd_D,SET5_IYd_E,SET5_IYd_H,SET5_IYd_L,SET5_IYd ,SET5_IYd_A,
		SET6_IYd_B,SET6_IYd_C,SET6_IYd_D,SET6_IYd_E,SET6_IYd_H,SET6_IYd_L,SET6_IYd ,SET6_IYd_A,
		SET7_IYd_B,SET7_IYd_C,SET7_IYd_D,SET7_IYd_E,SET7_IYd_H,SET7_IYd_L,SET7_IYd ,SET7_IYd_A,
};


extern u8	SZFlagsTable[256];
extern u8	SZPFlagsTable[256];
extern u16	DAATable[2048];
extern u8	Cycles[256];
extern u8	CyclesCB[256];
extern u8	CyclesDD[256];
extern u8	CyclesED[256];
extern u8	CyclesXXCB[256];
#endif





















